theme: jekyll-theme-hacker
show_downloads: false
title: NeuraSights
description: We create competitive advantage to drive business value and growth by deriving insights from (small and big) data using Neural Networks, Machine Learning and Artificial Intelligence.
