theme: jekyll-theme-hacker
show_downloads: false
title: NeuraSights
description: Ceating business intelligence and business insights from (small and big) data using Neural Networks, Machine Learning and Artificial Intelligence.
